using System.Collections.Generic;
using System.IO;

namespace CodeGenerator
{
    public class PermissionsBuilder
    {
        private const string FILENAME = "Permissions";
        private static string DirectoryLocation => Directory.GetCurrentDirectory();
        private static string FileLocation => Path.Combine(DirectoryLocation, FILENAME);

        public void BuildFile()
        {
            string autoGeneratedWarning = "********************************************************************************\n" +
                                          "NOTE: THIS IS AUTO GENERATED CONTENT! ANY CHANGES WILL BE DELETED ON NEXT BUILD \n " +
                                          "********************************************************************************";

            string includes = "using System;" +
                              "using System.Text;";

            string regionStart = "#region AutoGeneratedContent";

            string enumDefinition = "public enum Permissions \n" +
                                    "{ \n";

           // List<SecPermission> permissionList = 
        }
    }
}
