//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetLink
    {
        public int li_id { get; set; }
        public string li_location { get; set; }
        public int li_asid { get; set; }
        public int li_ltid { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual AssetLinkType AssetLinkType { get; set; }
    }
}
