/********************************************************************************
NOTE: THIS IS AUTO GENERATED CONTENT! ANY CHANGES WILL BE DELETED ON NEXT BUILD 
 *********************************************************************************/
using System;
using System.Text;
using System.ComponentModel;

namespace DomainModel 
{
	#region AutoGeneratedContent
	public enum Permission 
	{ 
		[Description("Modify Assignments")]
		ModifyAssignments = 1,

		[Description("Modify Phase -- Unassigned")]
		ModifyPhaseUnassigned = 2,

		[Description("Modify Phase -- Assigned")]
		ModifyPhaseAssigned = 3,

		[Description("Create Asset")]
		CreateAsset = 4,

		[Description("Delete Asset")]
		DeleteAsset = 5,

		[Description("Update Asset")]
		UpdateAsset = 6,

		[Description("Modify Asset Category")]
		ModifyAssetCategory = 7,

		[Description("Create User")]
		CreateUser = 8,

		[Description("Delete User")]
		DeleteUser = 9,

		[Description("Modify User Role")]
		ModifyUserRole = 10,

		[Description("Modify Notifications")]
		ModifyNotifications = 11,

		[Description("Modify Other User")]
		ModifyOtherUser = 12,

		[Description("Post Discussion")]
		PostDiscussion = 13,

		[Description("Edit User")]
		EditUser = 14,

		[Description("Clone User")]
		CloneUser = 15,

		[Description("Clone User Role")]
		CloneUserRole = 16,

		[Description("Delete User Role")]
		DeleteUserRole = 17,

		[Description("Delete Asset Category")]
		DeleteAssetCategory = 18,

		[Description("Clone Asset Category")]
		CloneAssetCategory = 19,

		[Description("Create Asset Category")]
		CreateAssetCategory = 20,

		[Description("Create User Role")]
		CreateUserRole = 21,

		[Description("Create Alert")]
		CreateAlert = 22,

		[Description("Modify Alert")]
		ModifyAlert = 23,

		[Description("Delete Alert")]
		DeleteAlert = 24,

	}
	#endregion
}
