/********************************************************************************
NOTE: THIS IS AUTO GENERATED CONTENT! ANY CHANGES WILL BE DELETED ON NEXT BUILD 
 *********************************************************************************/
using System;
using System.Text;
using System.ComponentModel;

namespace DomainModel 
{
	#region AutoGeneratedContent
	public enum Permission 
	{ 
		[Description("Modify Assignments")]
		ModifyAssignments = 1,

		[Description("Modify Phase -- Unassigned")]
		ModifyPhaseUnassigned = 2,

		[Description("Modify Phase -- Assigned")]
		ModifyPhaseAssigned = 3,

		[Description("Create Asset")]
		CreateAsset = 4,

		[Description("Delete Asset")]
		DeleteAsset = 5,

		[Description("Update Asset")]
		UpdateAsset = 6,

		[Description("Modify Asset Category")]
		ModifyAssetCategory = 7,

		[Description("Create User")]
		CreateUser = 8,

		[Description("Delete User")]
		DeleteUser = 9,

		[Description("Modify User Role")]
		ModifyUserRole = 10,

		[Description("Modify Notifications")]
		ModifyNotifications = 11,

		[Description("Modify Other User")]
		ModifyOtherUser = 12,

		[Description("Post Discussion")]
		PostDiscussion = 13,

	}
	#endregion
}
