//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetTracker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public int ar_id { get; set; }
        public string ar_type { get; set; }
        public Nullable<int> ar_asid { get; set; }
        public Nullable<int> ar_usid { get; set; }
        public Nullable<bool> ar_priority { get; set; }
        public Nullable<int> ar_recid { get; set; }
        public System.DateTime ar_date { get; set; }
        public bool ar_viewed { get; set; }
        public bool ar_projectwide { get; set; }
        public string ar_content { get; set; }
        public string ar_header { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual User User { get; set; }
    }
}
