//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetTracker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetConnection
    {
        public int ct_id { get; set; }
        public int ct_parentid { get; set; }
        public int ct_childid { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Asset Asset1 { get; set; }
    }
}
