//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetTracker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Change
    {
        public int ch_id { get; set; }
        public string ch_description { get; set; }
        public System.DateTime ch_datetime { get; set; }
        public string ch_oldvalue { get; set; }
        public string ch_newvalue { get; set; }
        public string ch_field { get; set; }
        public int ch_recid { get; set; }
        public int ch_usid { get; set; }
    }
}
