//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetTracker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecPermission2
    {
        public int p2_id { get; set; }
        public int p2_usid { get; set; }
        public int p2_prid { get; set; }
        public bool p2_allow { get; set; }
    
        public virtual SecPermission SecPermission { get; set; }
        public virtual User User { get; set; }
    }
}
